# Generated by Django 4.1.3 on 2023-01-02 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('criador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Conteúdos',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('criador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=100, verbose_name='série')),
                ('dificuldade', models.CharField(blank=True, choices=[('F', 'Fácil'), ('M', 'Média'), ('D', 'Difícil')], max_length=5, verbose_name='dificuldade')),
                ('enunciado', models.TextField(max_length=5000, verbose_name='enunciado')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='imagem')),
                ('comando', models.TextField(blank=True, max_length=5000, null=True, verbose_name='comando')),
                ('alternativa_a', models.TextField(blank=True, max_length=5000, null=True, verbose_name='alternativa A')),
                ('imagem_a', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='imagem A')),
                ('alternativa_b', models.TextField(blank=True, max_length=5000, null=True, verbose_name='alternativa B')),
                ('imagem_b', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='imagem B')),
                ('alternativa_c', models.TextField(blank=True, max_length=5000, null=True, verbose_name='alternativa C')),
                ('imagem_c', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='imagem C')),
                ('alternativa_d', models.TextField(blank=True, max_length=5000, null=True, verbose_name='alternativa C')),
                ('imagem_d', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='imagem D')),
                ('alternativa_e', models.TextField(blank=True, max_length=5000, null=True, verbose_name='alternativa E')),
                ('imagem_e', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='imagem E')),
                ('gabarito', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=5000, verbose_name='gabarito')),
                ('conteudo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elaboradorapp.conteudo', verbose_name='conteúdo')),
                ('criador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criador', to=settings.AUTH_USER_MODEL, verbose_name='criador')),
                ('disciplina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elaboradorapp.disciplina', verbose_name='disciplina')),
                ('vinculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vínculo')),
            ],
            options={
                'verbose_name': 'questão',
                'verbose_name_plural': 'questões',
                'ordering': ['disciplina', 'conteudo'],
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='images/', verbose_name='imagem')),
                ('criador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='conteudo',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elaboradorapp.disciplina'),
        ),
    ]
