# Generated by Django 4.1.3 on 2022-12-04 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=100, verbose_name='Serie')),
                ('dificuldade', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=5, verbose_name='Dificuldade')),
                ('enunciado', models.TextField(max_length=5000, verbose_name='Enunciado')),
                ('alternativa_a', models.TextField(max_length=5000, verbose_name='Alternativa_a')),
                ('alternativa_b', models.TextField(max_length=5000, verbose_name='Alternativa_b')),
                ('alternativa_c', models.TextField(max_length=5000, verbose_name='Alternativa_c')),
                ('alternativa_d', models.TextField(max_length=5000, verbose_name='Alternativa_d')),
                ('alternativa_e', models.TextField(max_length=5000, verbose_name='Alternativa_e')),
                ('gabarito', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=5000, verbose_name='Gabarito')),
                ('conteudo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elaboradorapp.conteudo')),
                ('disciplina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elaboradorapp.disciplina')),
            ],
        ),
        migrations.AddField(
            model_name='conteudo',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elaboradorapp.disciplina'),
        ),
    ]
