# Generated by Django 4.1.3 on 2022-12-24 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='images/', verbose_name='imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=100, verbose_name='Série')),
                ('dificuldade', models.CharField(blank=True, choices=[('F', 'Fácil'), ('M', 'Média'), ('D', 'Difícil')], max_length=5, verbose_name='Dificuldade')),
                ('enunciado', models.TextField(max_length=5000, verbose_name='Enunciado')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem')),
                ('comando', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Comando')),
                ('alternativa_a', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Alternativa A')),
                ('imagem_a', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem A')),
                ('alternativa_b', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Alternativa B')),
                ('imagem_b', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem B')),
                ('alternativa_c', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Alternativa C')),
                ('imagem_c', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem C')),
                ('alternativa_d', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Alternativa C')),
                ('imagem_d', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem D')),
                ('alternativa_e', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Alternativa E')),
                ('imagem_e', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem E')),
                ('gabarito', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=5000, verbose_name='Gabarito')),
                ('conteudo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elaboradorapp.conteudo', verbose_name='Conteúdo')),
                ('disciplina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elaboradorapp.disciplina', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'questão',
                'verbose_name_plural': 'questões',
                'ordering': ['disciplina', 'conteudo'],
            },
        ),
        migrations.AddField(
            model_name='conteudo',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elaboradorapp.disciplina'),
        ),
    ]
