# Generated by Django 4.1.3 on 2022-12-24 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elaboradorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vincular questão'),
        ),
    ]
