# Generated by Django 4.1.3 on 2023-01-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elaboradorapp', '0002_prova'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='nome_prova',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
