# Generated by Django 4.1.3 on 2022-12-31 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elaboradorapp', '0002_question_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conteudo',
            options={'verbose_name_plural': 'Conteúdos'},
        ),
        migrations.AlterField(
            model_name='question',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vincular questão'),
        ),
    ]
