# Generated by Django 4.1.3 on 2022-12-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elaboradorapp', '0003_alter_question_dificuldade_alter_question_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem'),
        ),
    ]
