# Generated by Django 4.1.3 on 2023-01-26 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elaboradorapp', '0003_prova_nome_prova'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prova',
            name='vinculo',
        ),
        migrations.AddField(
            model_name='prova',
            name='criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
