# Generated by Django 4.1.3 on 2022-12-31 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elaboradorapp', '0004_alter_question_autor_alter_question_gabarito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='alternativa_a',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='alternativa A'),
        ),
        migrations.AlterField(
            model_name='question',
            name='alternativa_b',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='alternativa B'),
        ),
        migrations.AlterField(
            model_name='question',
            name='alternativa_c',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='alternativa C'),
        ),
        migrations.AlterField(
            model_name='question',
            name='alternativa_d',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='alternativa C'),
        ),
        migrations.AlterField(
            model_name='question',
            name='alternativa_e',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='alternativa E'),
        ),
        migrations.AlterField(
            model_name='question',
            name='comando',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='comando'),
        ),
        migrations.AlterField(
            model_name='question',
            name='conteudo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elaboradorapp.conteudo', verbose_name='conteúdo'),
        ),
        migrations.AlterField(
            model_name='question',
            name='dificuldade',
            field=models.CharField(blank=True, choices=[('F', 'Fácil'), ('M', 'Média'), ('D', 'Difícil')], max_length=5, verbose_name='dificuldade'),
        ),
        migrations.AlterField(
            model_name='question',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elaboradorapp.disciplina', verbose_name='disciplina'),
        ),
        migrations.AlterField(
            model_name='question',
            name='enunciado',
            field=models.TextField(max_length=5000, verbose_name='enunciado'),
        ),
        migrations.AlterField(
            model_name='question',
            name='gabarito',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=5000, verbose_name='gabarito'),
        ),
        migrations.AlterField(
            model_name='question',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='question',
            name='imagem_a',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='imagem A'),
        ),
        migrations.AlterField(
            model_name='question',
            name='imagem_b',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='imagem B'),
        ),
        migrations.AlterField(
            model_name='question',
            name='imagem_c',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='imagem C'),
        ),
        migrations.AlterField(
            model_name='question',
            name='imagem_d',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='imagem D'),
        ),
        migrations.AlterField(
            model_name='question',
            name='imagem_e',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='imagem E'),
        ),
        migrations.AlterField(
            model_name='question',
            name='serie',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=100, verbose_name='série'),
        ),
    ]
