# Generated by Django 4.1.3 on 2022-12-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elaboradorapp', '0004_question_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='comando',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Comando'),
        ),
        migrations.AlterField(
            model_name='question',
            name='dificuldade',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5, verbose_name='Dificuldade'),
        ),
        migrations.AlterField(
            model_name='question',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='question',
            name='serie',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=100, verbose_name='Serie'),
        ),
    ]
