# Generated by Django 4.1.3 on 2023-02-02 17:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elaboradorapp', '0004_remove_prova_vinculo_prova_criador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='enunciado',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
