# Generated by Django 4.1.3 on 2022-12-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elaboradorapp', '0005_question_comando_alter_question_dificuldade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='imagem_a',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem_a'),
        ),
        migrations.AddField(
            model_name='question',
            name='imagem_b',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem_b'),
        ),
        migrations.AddField(
            model_name='question',
            name='imagem_c',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem_c'),
        ),
        migrations.AddField(
            model_name='question',
            name='imagem_d',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem_d'),
        ),
        migrations.AddField(
            model_name='question',
            name='imagem_e',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem_e'),
        ),
    ]
