# Generated by Django 4.1.3 on 2022-12-31 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elaboradorapp', '0005_alter_question_alternativa_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criador', to=settings.AUTH_USER_MODEL, verbose_name='criador'),
        ),
    ]
