# Generated by Django 4.1.3 on 2023-02-12 00:04

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elaboradorapp', '0006_alter_question_enunciado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='enunciado',
            field=django_quill.fields.QuillField(),
        ),
    ]
