# Generated by Django 4.1.3 on 2022-12-31 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elaboradorapp', '0006_question_criador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='autor',
            new_name='vinculo',
        ),
    ]
